/* Build with the port's 32-bit portable blst; stdout is a public constant. */
#include <stdio.h>
#include <blst.h>
#include <blst_aux.h>
int main(void) {
    blst_fp6 lines[68];
    blst_precompute_lines(lines, blst_p2_affine_generator());
    puts("/* Generated by tools/generate_bls_lines.c. Public BLS12-381 G2 generator. */");
    puts("static const blst_fp6 bls_generator_lines[68] = {");
    for (size_t i=0;i<68;i++) {
        puts("  { .fp2 = {");
        for (size_t j=0;j<3;j++) {
            puts("    { .fp = {");
            for (size_t k=0;k<2;k++) {
                printf("      { .l = {");
                for(size_t l=0;l<6;l++) printf("0x%016llxULL%s", (unsigned long long)lines[i].fp2[j].fp[k].l[l], l==5?"":",");
                puts("} },");
            }
            puts("    } },");
        }
        puts("  } },");
    }
    puts("};");
}
